version: "3"
services:
  openwrt_build:
    build:
      context: .
      dockerfile: Dockerfile
    image: mingmxren/openwrt_build:latest
    container_name: openwrt_build
    hostname: openwrt_build
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - FORCE_UNSAFE_CONFIGURE=1
    volumes:
      - /data/openwrt_build:/build
